title: Nasser Kazemi- Personal Website - Comming soon
logo: /assets/img/logo.png
description: Assistant Professor of Applied Geophysics.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
